#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

if [[ ! -f flake.nix || ! -f dot27_home.nix ]]; then
    echo "Run this from the root of the dot27 repo (flake.nix / dot27_home.nix not found here)." >&2
    exit 1
fi

OLD_USER="lmtot27"
OLD_USER_MIXED="lmToT27"
ETC_NIXOS="/etc/nixos"

esc() {
    printf '%s' "$1" | sed -e 's/[\&#]/\\&/g'
}

read -rp "Linux username [$(whoami)]: " NEW_USER
NEW_USER="${NEW_USER:-$(whoami)}"

read -rp "Full name (for the account description) [$NEW_USER]: " FULL_NAME
FULL_NAME="${FULL_NAME:-$NEW_USER}"

read -rp "Git user.name [$NEW_USER]: " GIT_NAME
GIT_NAME="${GIT_NAME:-$NEW_USER}"

read -rp "Git user.email: " GIT_EMAIL

NEW_USER_ESC="$(esc "$NEW_USER")"
FULL_NAME_ESC="$(esc "$FULL_NAME")"
GIT_NAME_ESC="$(esc "$GIT_NAME")"
GIT_EMAIL_ESC="$(esc "$GIT_EMAIL")"

sudo mkdir -p "$ETC_NIXOS"

DOT27_MARKER="# Generated by dot27 install.sh — safe to hand-edit, re-running install.sh will not touch it again"

generate_from_example() {
    local name="$1"
    local dest="$ETC_NIXOS/$name"

    if [[ -f "$dest" ]] && grep -qF "$DOT27_MARKER" "$dest"; then
        echo "==> $dest already generated by dot27 install.sh, leaving it alone"
        return
    fi

    if [[ -f "$dest" ]]; then
        local backup="${dest}.orig-$(date +%s)"
        echo "==> $dest exists but wasn't generated by dot27 (backing up to $backup)"
        sudo cp "$dest" "$backup"
    fi

    echo "==> Generating $dest from etc-nixos/${name}.example"
    local tmp
    tmp="$(mktemp)"
    {
        echo "$DOT27_MARKER"
        cat "etc-nixos/${name}.example"
    } > "$tmp"
    sed -i "s#path:/home/${OLD_USER}/dot27#path:${SCRIPT_DIR}#" "$tmp"
    sed -i "s#${OLD_USER}#${NEW_USER_ESC}#g" "$tmp"
    sed -i "s#description = \"Le Minh Tuan\";#description = \"${FULL_NAME_ESC}\";#" "$tmp"
    sed -i "s#user\.name = \"${OLD_USER_MIXED}\";#user.name = \"${GIT_NAME_ESC}\";#" "$tmp"
    sed -i "s#user\.email = \"[^\"]*\";#user.email = \"${GIT_EMAIL_ESC}\";#" "$tmp"
    sudo cp "$tmp" "$dest"
    sudo chmod 644 "$dest"
    rm -f "$tmp"
}

generate_from_example "configuration.nix"
generate_from_example "home.nix"
generate_from_example "flake.nix"

echo "==> Regenerating hardware-configuration.nix for this machine"
sudo nixos-generate-config --show-hardware-config | sudo tee "$ETC_NIXOS/hardware-configuration.nix" > /dev/null

if [[ ! -d sddm ]]; then
    echo "==> Cloning SDDM theme"
    git clone --depth 1 https://github.com/stepanzubkov/where-is-my-sddm-theme.git sddm
else
    echo "==> ./sddm already present, skipping clone"
fi

cat <<EOF

Done. $ETC_NIXOS now has its own flake that depends on this repo
(path:$SCRIPT_DIR) via the "dot27" input.

Before rebuilding, review:
  - hardware.nvidia.prime bus IDs / services.xserver.videoDrivers in $ETC_NIXOS/configuration.nix
    (written for this machine's AMD+NVIDIA Prime setup; adjust or remove for yours)
  - time.timeZone / i18n / fcitx5 block in $ETC_NIXOS/configuration.nix (set for vi_VN)
  - place a ~/.face.icon, or remove the sddm-avatar activationScript in
    $ETC_NIXOS/configuration.nix, or its "cp" will fail on activation
  - $ETC_NIXOS/home.nix has the Data Science/AI packages (kaggle, visidata, ruff,
    the python3.withPackages block) — trim or extend as you like

Then run (from anywhere, /etc/nixos is the default flake path):
  sudo nixos-rebuild switch --update-input dot27
EOF
