font_family      JetBrainsMono Nerd Font
font_size        21.0

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

cursor_shape beam
cursor_blink_interval 1
cursor_trail 2
cursor_trail_decay 0.1 0.4

background_opacity 0.85
window_padding_width 4
